[project]
name = "spark-cluster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "delta-spark>=4.0.0",
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "pyspark>=4.0.0",    
    "pyspark[connect]"
]
