services:
  spark-master:
    image: bitnami/spark:4.0.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_HOST=spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-network
    volumes:
      - ./temp_data:/data
      - ./temp_data/logs:/opt/bitnami/spark/logs

  spark-connect:
    image: bitnami/spark:4.0.0
    container_name: spark-connect
    environment:      
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - 15002:15002
    networks:
      - spark-network
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/sbin/start-connect-server.sh --conf spark.master=spark://spark-master:7077 --packages org.apache.spark:spark-connect_2.13:4.0.0"]
    volumes:      
      - ./temp_data/logs:/opt/spark/logs

  spark-worker:
    image: bitnami/spark:4.0.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:      
      - ./temp_data/logs:/opt/bitnami/spark/logs

  spark-worker2:
    image: bitnami/spark:4.0.0
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_WEBUI_PORT=8082
    ports:
      - 8082:8082
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:      
      - ./temp_data/logs:/opt/bitnami/spark/logs

networks:
  spark-network: